ui: tape
browsers:
  - name: chrome
    version: 30..latest
  - name: firefox
    version: 29..latest
  - name: safari
    version: 5..latest
  - name: opera
    version: latest
scripts:
  - './node_modules/pouchdb/dist/pouchdb.js'
  - './node_modules/pouchdb/dist/pouchdb.memory.js'
